In [1]:
import torch

## Lets play with torch for a while to get used to it

In [2]:
four_by_five = torch.randn(4, 5)
print("a tensor")
print(four_by_five)
print("first row", four_by_five[0])

print("first column")
col1 = torch.select(four_by_five, 1, 0)
print(col1)

col1[0] = 2.4
print("tensor after changing[0][0]", four_by_five)
print("first column using slice")
print(four_by_five[:,0])

four_by_four = four_by_five[:,0:4]

tril = torch.tril(torch.ones(4,4))
print("a left (lower) triangluar matric")
print(tril)

print("our original matric mutlipled by the left triangular matrix") 
four_by_four * tril

a tensor
tensor([[-1.7526, -0.6130, -1.9947,  0.8156, -1.2796],
        [ 1.3196, -1.3459, -1.3788,  0.3734, -0.0524],
        [ 0.8171, -0.2849,  0.9884, -0.1884, -0.7868],
        [-0.8577, -0.2184, -0.3566, -0.0097, -0.9393]])
first row tensor([-1.7526, -0.6130, -1.9947,  0.8156, -1.2796])
first column
tensor([-1.7526,  1.3196,  0.8171, -0.8577])
tensor after changing[0][0] tensor([[ 2.4000, -0.6130, -1.9947,  0.8156, -1.2796],
        [ 1.3196, -1.3459, -1.3788,  0.3734, -0.0524],
        [ 0.8171, -0.2849,  0.9884, -0.1884, -0.7868],
        [-0.8577, -0.2184, -0.3566, -0.0097, -0.9393]])
first column using slice
tensor([ 2.4000,  1.3196,  0.8171, -0.8577])
a left (lower) triangluar matric
tensor([[1., 0., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 1.]])
our original matric mutlipled by the left triangular matrix


tensor([[ 2.4000, -0.0000, -0.0000,  0.0000],
        [ 1.3196, -1.3459, -0.0000,  0.0000],
        [ 0.8171, -0.2849,  0.9884, -0.0000],
        [-0.8577, -0.2184, -0.3566, -0.0097]])

## B, T, C

what's this B, T, C stuff?

Lets use it to get used to some more stuff

it's maybe not super clear
* B - is the Batch Dimension

so if we have 3 examples in a Batch and each example is 4 tokens long

In [3]:
BT = torch.randn(3, 4)
BT

tensor([[ 0.6932,  1.1297,  0.1804,  2.0001],
        [-1.6543,  0.1379,  1.9224,  0.8588],
        [ 0.9539,  1.3666, -0.7944, -0.3785]])



so the first example in the batch is BT[0], the second BT[1] etc...

so the first index place is the B (batch) and the chosen index is the example

* T is for time

then within the example T is the Time dimension refering to it this way is confusing in our language model

what's time got to do with it?

it's from thinking of the example as a sequence, one element following another (Like as the waves make towards the pebbl'd shore)

so if we have a 3x4 batch:

[ 
 [w, h, e, n],
 [b. o, t, h],
 [w, h, a, t],
]

here we can see the time dimension for the first example in the batch 

| B       | T        |          |
| :-----: | :------: | :------: |
| [0]     | [0]      | -> w     |
| [0]     | [1]      | -> h     |
| [0]     | [2]      | -> e     |
| [0]     | [3]      | -> n     |




## C is for Channel
say we've embedded our letters in a two dimensional space, each dimension is a channel

or in an image, a pixel could have 3 colour 'channels' RGB

we'll start with 2 channels

In [4]:
BTC = torch.randn(3, 4, 2)
BTC

tensor([[[-0.4868,  0.3267],
         [ 0.0085,  0.1575],
         [ 0.9436,  0.0135],
         [ 0.6672,  0.1382]],

        [[-1.0947, -0.7651],
         [-0.5687, -0.6855],
         [-0.7222,  1.0697],
         [ 0.5297, -1.1687]],

        [[ 0.9568, -0.7414],
         [-0.1002,  0.5613],
         [ 0.0028,  1.1634],
         [-0.5339, -1.4513]]])

so now our 'w' in when is represented by 2 numbers - a duple, the first element of the sequence of the first example in the batch

In [5]:
w = BTC[0, 0]
print("w", w)
w_ChannelX = w[0]
w_ChannelY = w[1]
"X", w_ChannelX, "Y", w_ChannelY

w tensor([-0.4868,  0.3267])


('X', tensor(-0.4868), 'Y', tensor(0.3267))

## Read a book
lets read some lines from a book and play with them

In [6]:
%run ../lib/bookreader.py

In [7]:
br = BookReader()

br.read("../resources/alice.txt")

print("number of symbols", br.vocab_size, "lengths of our train, dev, test splits", len(br.data[0]), len(br.data[1]), len(br.data[2]))
print("the symbols with their int representations (zero is a newline)")
symbols = ""
for i, c in enumerate(br.chars):
    symbols += f"{i}:{c}, "
print(symbols)
encodedText = torch.tensor(br.data[0][:400])
print("the text with each character encoded to an int in our lookup")
print(encodedText)
print("the text decoded from the int representations")
br.decode(encodedText.tolist())

lowercase only
number of symbols 29 lengths of our train, dev, test splits 2525 0 0
the symbols with their int representations (zero is a newline)
0:
, 1: , 2:!, 3:?, 4:a, 5:b, 6:c, 7:d, 8:e, 9:f, 10:g, 11:h, 12:i, 13:j, 14:k, 15:l, 16:m, 17:n, 18:o, 19:p, 20:q, 21:r, 22:s, 23:t, 24:u, 25:v, 26:w, 27:x, 28:y, 
the text with each character encoded to an int in our lookup
tensor([ 4, 15, 12,  6,  8,  1, 26,  4, 22,  1,  5,  8, 10, 12, 17, 17, 12, 17,
        10,  1, 23, 18,  1, 10,  8, 23,  1, 25,  8, 21, 28,  1, 23, 12, 21,  8,
         7,  1, 18,  9,  1, 22, 12, 23, 23, 12, 17, 10,  1,  5, 28,  1, 11,  8,
        21,  1, 22, 12, 22, 23,  8, 21,  1, 18, 17,  1, 23, 11,  8,  0,  5,  4,
        17, 14,  1,  1,  4, 17,  7,  1, 18,  9,  1, 11,  4, 25, 12, 17, 10,  1,
        17, 18, 23, 11, 12, 17, 10,  1, 23, 18,  1,  7, 18,  1,  1, 18, 17,  6,
         8,  1, 18, 21,  1, 23, 26, 12,  6,  8,  1, 22, 11,  8,  1, 11,  4,  7,
         1, 19,  8,  8, 19,  8,  7,  1, 12, 17, 23, 18,  0, 23, 11,

'alice was beginning to get very tired of sitting by her sister on the\nbank  and of having nothing to do  once or twice she had peeped into\nthe book her sister was reading  but it had no pictures or\nconversations in it   and what is the use of a book   thought alice\n without pictures or conversations? \n\nso she was considering in her own mind  as well as she could  for the\nhot day made her feel very'

## Data loading
typically we want to get batches of a given sequence length from one of our train, dev, test data sets

for sequence length we want the combined length of the example and the target - we tend to use x and y in our code

so for our texts the examples each have context length number of symbols and the labels are what follows (typically a single symbol in our simple models)

so to use get_batch to get a batch 5 sequences which each contain 5 symbols and their labels of length 1 we can call

get_batch(train, 6, 5)

below we show we can choose any value >=6 and use splits to form our x and y

In [8]:
# data loading
def get_batch(data, batch_length=5, batch_size=5):
    # generate a small batch of data of inputs x and targets y
    ix = torch.randint(len(data) - batch_length, (batch_size,))
    b = torch.stack([data[i:i+batch_length] for i in ix])
    return b

big_size = 32
batch_one = get_batch(encodedText, big_size)
batch_one

tensor([[22, 12, 22, 23,  8, 21,  1, 26,  4, 22,  1, 21,  8,  4,  7, 12, 17, 10,
          1,  1,  5, 24, 23,  1, 12, 23,  1, 11,  4,  7,  1, 17],
        [ 4, 15, 12,  6,  8,  1, 26,  4, 22,  1,  5,  8, 10, 12, 17, 17, 12, 17,
         10,  1, 23, 18,  1, 10,  8, 23,  1, 25,  8, 21, 28,  1],
        [ 8, 21, 22,  4, 23, 12, 18, 17, 22,  3,  1,  0,  0, 22, 18,  1, 22, 11,
          8,  1, 26,  4, 22,  1,  6, 18, 17, 22, 12,  7,  8, 21],
        [ 4, 15, 12,  6,  8,  1, 26,  4, 22,  1,  5,  8, 10, 12, 17, 17, 12, 17,
         10,  1, 23, 18,  1, 10,  8, 23,  1, 25,  8, 21, 28,  1],
        [ 8,  1, 26,  4, 22,  1,  5,  8, 10, 12, 17, 17, 12, 17, 10,  1, 23, 18,
          1, 10,  8, 23,  1, 25,  8, 21, 28,  1, 23, 12, 21,  8]])

In [10]:
for i in range(5):
    print("b: ", br.decode(batch_one[i].tolist()))

b:  sister was reading  but it had n
b:  alice was beginning to get very 
b:  ersations? 

so she was consider
b:  alice was beginning to get very 
b:  e was beginning to get very tire


## X and Y

so we can decide after what we want to do with the batch we got

from above we know we can index into things easily

so we can create an X batch and their Ys as we like, say we wanted Xs of length 4 and we wanted to see Ys of length 3 in our cross_entropy

(we just do this so it's easy to see our Ys are the correct following letters)

In [13]:
context_length = 4
x = batch_one[:, 0:context_length]
y = batch_one[:, context_length:context_length+3]
print(x, y)
for i in range(5):
    print("xy: ", br.decode(x[i].tolist()), "-> ", br.decode(y[i].tolist()))

tensor([[22, 12, 22, 23],
        [ 4, 15, 12,  6],
        [ 8, 21, 22,  4],
        [ 4, 15, 12,  6],
        [ 8,  1, 26,  4]]) tensor([[ 8, 21,  1],
        [ 8,  1, 26],
        [23, 12, 18],
        [ 8,  1, 26],
        [22,  1,  5]])
xy:  sist ->  er 
xy:  alic ->  e w
xy:  ersa ->  tio
xy:  alic ->  e w
xy:  e wa ->  s b


## or just do it all at once...

In [15]:
def get_labeled_batch(data, context_length=4, label_length=1, batch_size=5):
    # generate a small batch of data of inputs x and targets y
    ix = torch.randint(len(data) - context_length, (batch_size,))
    b = torch.stack([data[i:i+context_length+label_length] for i in ix])
    
    x = b[:, 0:context_length]
    y = b[:, context_length:context_length+label_length]
    return x, y

X, Y = get_labeled_batch(encodedText)
for i in range(5):
    print("xy: ", br.decode(X[i].tolist()), "-> ", br.decode(Y[i].tolist()))

xy:  e or ->   
xy:   con ->  s
xy:   con ->  s
xy:  ing  ->  i
xy:  ter  ->  w


## multiple examples from a single batch element

to get more out of our context we go back to the get_batch() implementation because we want to make multiple examples from a single example 

looking at a sequence 'alice ' we can form the following
* a.... -> e
* al... -> i
* ali.. -> c
* alic. -> e
* alice ->

so now we want to form the labels for all 5 all at once ['e', 'i', 'c', 'e', ' ']
and we can see if we get context_length+1 our example is just [:-1] and our label is just [1:] 

## a shortcut to mushrooms

we can form these examples using a triangular matric

In [16]:
tr = torch.tril(torch.ones((4, 4), dtype=torch.int))
tr

tensor([[1, 0, 0, 0],
        [1, 1, 0, 0],
        [1, 1, 1, 0],
        [1, 1, 1, 1]], dtype=torch.int32)

if alice was encoded [a->1, l->2, i->3, c->4, e->5]

then using our tensor tr we get

In [17]:
al = torch.tensor(range(1, 5))
st = al.repeat(1, 4)
bt = al * tr
bt

tensor([[1, 0, 0, 0],
        [1, 2, 0, 0],
        [1, 2, 3, 0],
        [1, 2, 3, 4]])

## We can batch our batch too 

using a 3 dimensional triangular tensor

In [18]:
context_length = 4
batch_one = get_batch(encodedText, context_length + 1)
x = batch_one[:, 0:context_length]

tr = torch.tril(torch.ones((5, 4, 4), dtype=torch.int))

mult = x.repeat(1, 1, 4)
print(mult, mult.shape)
print(mult.view(5, 4, 4))

lower_batch = mult.view(5, 4, 4) * tr
lower_batch

tensor([[[ 4,  1,  5, 18,  4,  1,  5, 18,  4,  1,  5, 18,  4,  1,  5, 18],
         [18, 17, 22, 12, 18, 17, 22, 12, 18, 17, 22, 12, 18, 17, 22, 12],
         [17,  1, 11,  8, 17,  1, 11,  8, 17,  1, 11,  8, 17,  1, 11,  8],
         [18,  1, 22, 11, 18,  1, 22, 11, 18,  1, 22, 11, 18,  1, 22, 11],
         [ 1, 22, 12, 22,  1, 22, 12, 22,  1, 22, 12, 22,  1, 22, 12, 22]]]) torch.Size([1, 5, 16])
tensor([[[ 4,  1,  5, 18],
         [ 4,  1,  5, 18],
         [ 4,  1,  5, 18],
         [ 4,  1,  5, 18]],

        [[18, 17, 22, 12],
         [18, 17, 22, 12],
         [18, 17, 22, 12],
         [18, 17, 22, 12]],

        [[17,  1, 11,  8],
         [17,  1, 11,  8],
         [17,  1, 11,  8],
         [17,  1, 11,  8]],

        [[18,  1, 22, 11],
         [18,  1, 22, 11],
         [18,  1, 22, 11],
         [18,  1, 22, 11]],

        [[ 1, 22, 12, 22],
         [ 1, 22, 12, 22],
         [ 1, 22, 12, 22],
         [ 1, 22, 12, 22]]])


tensor([[[ 4,  0,  0,  0],
         [ 4,  1,  0,  0],
         [ 4,  1,  5,  0],
         [ 4,  1,  5, 18]],

        [[18,  0,  0,  0],
         [18, 17,  0,  0],
         [18, 17, 22,  0],
         [18, 17, 22, 12]],

        [[17,  0,  0,  0],
         [17,  1,  0,  0],
         [17,  1, 11,  0],
         [17,  1, 11,  8]],

        [[18,  0,  0,  0],
         [18,  1,  0,  0],
         [18,  1, 22,  0],
         [18,  1, 22, 11]],

        [[ 1,  0,  0,  0],
         [ 1, 22,  0,  0],
         [ 1, 22, 12,  0],
         [ 1, 22, 12, 22]]])

Now say we put these through something to calculate the next character all the examples in each batch 

we can see that the solution for the first batch, batch is as expected

In [19]:
print(lower_batch[0])
batch_no = 0
y = batch_one[batch_no, batch_no+1: batch_no+context_length+1]
y

tensor([[ 4,  0,  0,  0],
        [ 4,  1,  0,  0],
        [ 4,  1,  5,  0],
        [ 4,  1,  5, 18]])


tensor([ 1,  5, 18, 18])

In [20]:
ys = y = batch_one[:, batch_no+1: batch_no+context_length+1]

print(lower_batch.shape, ys.shape)

lower_batch.view(-1), ys.reshape(20)

torch.Size([5, 4, 4]) torch.Size([5, 4])


(tensor([ 4,  0,  0,  0,  4,  1,  0,  0,  4,  1,  5,  0,  4,  1,  5, 18, 18,  0,
          0,  0, 18, 17,  0,  0, 18, 17, 22,  0, 18, 17, 22, 12, 17,  0,  0,  0,
         17,  1,  0,  0, 17,  1, 11,  0, 17,  1, 11,  8, 18,  0,  0,  0, 18,  1,
          0,  0, 18,  1, 22,  0, 18,  1, 22, 11,  1,  0,  0,  0,  1, 22,  0,  0,
          1, 22, 12,  0,  1, 22, 12, 22]),
 tensor([ 1,  5, 18, 18, 17, 22, 12,  7,  1, 11,  8, 21,  1, 22, 11,  8, 22, 12,
         22, 23]))

## Next

